version: '1'
services:
  web:
   build: 
     context: .
     dockerfile: Dockerfile.dev
   ports:
     - "3000:3000"
   volumes:
     - /usr/frontend/node_modules
     - .:/usr/frontend
  tests:
   build: 
     context: .
     dockerfile: Dockerfile.dev
   volumes:
     - /usr/frontend/node_modules
     - .:/usr/frontend
   command: ["npm", "run", "test"]